### ISSUE TITLE
AmazonS3Client warning about buffering content in memory

### ISSUE THREAD

**Issue by varju** [sonatype/nexus-blobstore-s3#15]
* **What are you trying to do?**

Testing with Nexus 3.6.0-02 and a local version of the plugin built off of 4d2934e.  While reviewing my logs I noticed many instances of:

```
[s3-transfer-manager-worker-1] *UNKNOWN com.amazonaws.services.s3.AmazonS3Client - No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
```

* **What feature or behavior is this required for?**

This appears to be triggered for any writes to the blob store.  We sometimes store very large artifacts, and I'm worried that this will explode our heap.

* **How could we solve this issue? (Not knowing is okay!)**

Perhaps get the content-length header from the incoming request, and change the blob api to include this?  Or temporarily store the file on disk before streaming to S3?

* **Anything else?**

I'm really excited about this plugin, and hope that it makes it to production grade in the near future.

**Comment by cfifua** [comment]
I have the same problem:
{code}
2017-11-07 14:27:24,108+0000 WARN  [s3-transfer-manager-worker-1] admin com.amazonaws.services.s3.AmazonS3Client - No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
{code}

**Comment by GregoireW** [comment]
Hello,

If you use S3, there is 2 uploading way:
- you put the file 100% in memory and you push the data
- you use multipart uploading so that you can push chunck of x MB of file.

This PR use the first solution and hide the fact that you put the file 100% in memory. If you use big file  you can have issue. 
Another approach, the multipart one, is implemented on the multipart-ui branch.

**Comment by OleksandrSlobodian** [comment]
Hello,

Have issue with docker-registry and store 100% in memory, same-time artifact build from multipart-ui branch works weird - there is no possibility to create s3 blob store ...

**Comment by GregoireW** [comment]
Hello,

The multipart branch is build against a nexus 3.5. Nexus 3.6 change a lot
of thing. I think I will re-push a new build with needed change.


Grégoire

2017-12-15 16:57 GMT+01:00 Oleksandr Slobodian <notifications@github.com>:

**Comment by OleksandrSlobodian** [comment]
Thanks!

**Comment by GregoireW** [comment]
Hi 
I push the merge request https://github.com/sonatype/nexus-blobstore-s3/pull/37  with multipart and nexus 3.6. If you want to check/test.

**Comment by OleksandrSlobodian** [comment]
Great, thanks, tested:
can create new s3 blob store... but unfortunately got error:

```
2017-12-16 19:35:56,211+0000 ERROR [qtp468409874-51] admin org.sonatype.nexus.extdirect.internal.ExtDirectServlet - Failed to invoke action method: coreui_Blobstore.create, java-method: org.sonatype.nexus.coreui.BlobStoreComponent.create
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but the 4th parameter of org.sonatype.nexus.blobstore.s3.internal.S3BlobStore.<init>(S3BlobStore.java:161) is not @Nullable
  while locating org.sonatype.nexus.blobstore.s3.internal.S3BlobStoreMetricsStore
    for the 4th parameter of org.sonatype.nexus.blobstore.s3.internal.S3BlobStore.<init>(S3BlobStore.java:161)
  while locating org.sonatype.nexus.blobstore.s3.internal.S3BlobStore
  while locating java.lang.Object annotated with *

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at org.sonatype.nexus.repository.internal.blobstore.BlobStoreManagerImpl.newBlobStore(BlobStoreManagerImpl.java:200)
	at org.sonatype.nexus.repository.internal.blobstore.BlobStoreManagerImpl.create(BlobStoreManagerImpl.java:150)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:270)
	at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:53)
	at org.sonatype.nexus.blobstore.api.BlobStoreManager$create$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.sonatype.nexus.coreui.BlobStoreComponent.create(BlobStoreComponent.groovy:88)
	at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:49)
	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:47)
	at org.sonatype.nexus.validation.internal.ValidationInterceptor.invoke(ValidationInterceptor.java:53)
	at org.apache.shiro.guice.aop.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:49)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.apache.shiro.guice.aop.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeJavaMethod(DispatcherBase.java:142)
	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeMethod(DispatcherBase.java:133)
	at org.sonatype.nexus.extdirect.internal.ExtDirectServlet$3.invokeMethod(ExtDirectServlet.java:233)
	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.dispatch(DispatcherBase.java:63)
	at com.softwarementors.extjs.djn.router.processor.standard.StandardRequestProcessorBase.dispatchStandardMethod(StandardRequestProcessorBase.java:73)
	at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequest(JsonRequestProcessor.java:502)
	at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequestsInThisThread(JsonRequestProcessor.java:150)
	at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.process(JsonRequestProcessor.java:133)
	at com.softwarementors.extjs.djn.router.RequestRouter.processJsonRequest(RequestRouter.java:83)
	at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.processRequest(DirectJNgineServlet.java:617)
	at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.doPost(DirectJNgineServlet.java:580)
	at org.sonatype.nexus.extdirect.internal.ExtDirectServlet.doPost(ExtDirectServlet.java:138)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:85)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:101)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:108)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:68)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:102)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:98)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.DynamicFilterPipeline.dispatch(DynamicFilterPipeline.java:104)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.sonatype.nexus.bootstrap.osgi.DelegatingFilter.doFilter(DelegatingFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:175)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by GregoireW** [comment]
which nexus version are you using ?  on a server (standalone) / docker / ...
What is the method you use to inject the plugin into nexus ?    (do you clean the old one? ) 

I'm not sure how it is even possible to have this error. The plugin give you the objects S3BlobStoreMetricsStore and S3BlobStore. The two have \@Named annotation, it means guice should have picked the two (or none if there is configuration error).  So why it is complaining about the missing S3BlobStoreMetricsStore on S3BlobStore...  (? out of memory before ? )

**Comment by OleksandrSlobodian** [comment]
Using: 
3.6.0-0.2 Nexus in docker ( https://github.com/sonatype/docker-nexus3 )
injection method from install.sh ( during docker build, so yes always clean )
this method works fine for master-branch artifact

**Comment by OleksandrSlobodian** [comment]
Using: 
3.6.0-0.2 Nexus in docker ( https://github.com/sonatype/docker-nexus3 )
injection method from install.sh ( during docker build, so yes always clean )
this method works fine for master-branch artifact

_META-INF/sisu/javax.inject.Named_
```
org.sonatype.nexus.blobstore.s3.internal.AmazonS3Factory
org.sonatype.nexus.blobstore.s3.internal.S3BlobStoreDescriptor
org.sonatype.nexus.blobstore.s3.internal.S3BlobStore
org.sonatype.nexus.blobstore.s3.internal.S3BlobStoreMetricsStore
```

**Comment by GregoireW** [comment]
Ah!

There was change between 3.6.0 and 3.6.1.  The branch is build against 3.6.1 and use some classes that seems to have been refactored.  Best option: upgrade to 3.6.2 (there should be less bug :D )

**Comment by OleksandrSlobodian** [comment]
Great!!! works like charm, excellent job! Thanks so much!

Truly believe that multi-part uploading is the only one right approach to upload blobs to S3, cant get why master branch works with in-memory store file before upload...

PS theres warning in logs during push to nexus:
```
2017-12-17 21:56:05,734+0000 WARN  [qtp618371783-40] test com.amazonaws.services.s3.internal.S3AbortableInputStream - Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
```

**Comment by GregoireW** [comment]
Hello,

If only we can close this issue now ;) 

For the warning, I will explain you the process: 
- You upload a file, file is put in S3 in a temporary blob 
- Nexus will then read back some byte of the file (the first few kb) to detect the MIME type of the file (hence the warning you got)
- Nexus will then send the command to copy the blob to final location: ( a S3 copy command) then another command to delete the temporary blob (a S3 delete blob command). 

I sent a mail a few month back to somebody in sonatype to know if they can modify the internal nexus process to 
- add like a wiretap (teestream, ...) to get the first kb when we send the full stream to storage, so that re-read the file is not required (faster and no logs on S3) 
- ask if they can delegate some security thing (create temporary file...) to blob implementation. For instance, on file blobstore, you will create a temporary file then use the move command. On S3, you can build the blob in place (no need to duplicate call)

I've got no answer on that...

**Comment by OleksandrSlobodian** [comment]
Thanks again, great plugin, brings nexus to other dimension.

**Comment by ju2wheels** [comment]
I think im hitting this issue and blowing the heap on my instance. Im trying to upload a 1.7GB file to a raw repository using a simple curl which is using a PUT. Does your explanation of in memory vs multipart chunking mean that if we use PUT its always going into memory and I should be using POST (if raw repo even supports that) so that it gets chunked instead?

**Comment by GregoireW** [comment]
Did you use the multipart branch ?      It should resolve your issue.

**Comment by ju2wheels** [comment]
@GregoireW 

The multipart-ul branch doesnt seem to compile against a 3.9.0-01 nexus-components:

```
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobAttributes.java:[38,14] 1. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobAttributes.java (at line 38)
	public class S3BlobAttributes implements BlobAttributes
	             ^^^^^^^^^^^^^^^^
The type S3BlobAttributes must implement the inherited abstract method BlobAttributes.updateFrom(BlobAttributes)

[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStoreMetricsStore.java:[145,49] 2. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStoreMetricsStore.java (at line 145)
	AccumulatingBlobStoreMetrics blobStoreMetrics = new AccumulatingBlobStoreMetrics(0, 0, Long.MAX_VALUE);
	                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The constructor AccumulatingBlobStoreMetrics(int, int, long) is undefined

[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java:[83,14] 3. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java (at line 83)
	public class S3BlobStore
	             ^^^^^^^^^^^
The type S3BlobStore must implement the inherited abstract method BlobStore.setBlobAttributes(BlobId, BlobAttributes)

[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java:[83,14] 4. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java (at line 83)
	public class S3BlobStore
	             ^^^^^^^^^^^
The type S3BlobStore must implement the inherited abstract method BlobStore.get(BlobId, boolean)

[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java:[83,14] 5. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java (at line 83)
	public class S3BlobStore
	             ^^^^^^^^^^^
The type S3BlobStore must implement the inherited abstract method BlobStore.getDirectPathBlobIdStream(String)

[ERROR] Found 5 errors and 0 warnings.
[INFO] 6 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:37 min
[INFO] Finished at: 2018-05-10T16:56:08Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project nexus-blobstore-s3: Compilation failure: Compilation failure: 
[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobAttributes.java:[38,14] 1. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobAttributes.java (at line 38)
[ERROR] 	public class S3BlobAttributes implements BlobAttributes
[ERROR] 	             ^^^^^^^^^^^^^^^^
[ERROR] The type S3BlobAttributes must implement the inherited abstract method BlobAttributes.updateFrom(BlobAttributes)
[ERROR] 
[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStoreMetricsStore.java:[145,49] 2. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStoreMetricsStore.java (at line 145)
[ERROR] 	AccumulatingBlobStoreMetrics blobStoreMetrics = new AccumulatingBlobStoreMetrics(0, 0, Long.MAX_VALUE);
[ERROR] 	                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The constructor AccumulatingBlobStoreMetrics(int, int, long) is undefined
[ERROR] 
[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java:[83,14] 3. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java (at line 83)
[ERROR] 	public class S3BlobStore
[ERROR] 	             ^^^^^^^^^^^
[ERROR] The type S3BlobStore must implement the inherited abstract method BlobStore.setBlobAttributes(BlobId, BlobAttributes)
[ERROR] 
[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java:[83,14] 4. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java (at line 83)
[ERROR] 	public class S3BlobStore
[ERROR] 	             ^^^^^^^^^^^
[ERROR] The type S3BlobStore must implement the inherited abstract method BlobStore.get(BlobId, boolean)
[ERROR] 
[ERROR] /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java:[83,14] 5. ERROR in /nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java (at line 83)
[ERROR] 	public class S3BlobStore
[ERROR] 	             ^^^^^^^^^^^
[ERROR] The type S3BlobStore must implement the inherited abstract method BlobStore.getDirectPathBlobIdStream(String)
[ERROR] 
[ERROR] Found 5 errors and 0 warnings.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by rwd5213** [comment]
@GregoireW Your PR worked fine when installed on nexus 3.6 however we still see the memory buffer content in the logs

**Comment by GregoireW** [comment]
If you have something like

> No content length specified for stream data. Stream contents will be buffered in memory and could result in out of memory errors.

then it means the version of the jar is not correct (or you forgot to remove the old jar :D )

If it is something like

> stream is partially read you should specify the length you want to receive for performance purpose

then it is an internal stuff on nexus, and I cannot really change that except by rewriting a big part of storage process.

**Comment by rwd5213** [comment]
We definitely see the first one. Does this mean we are not using the version of the jar from your branch?

**Comment by GregoireW** [comment]
Yes, it means it is not the correct plugin that is loaded.

**Comment by rwd5213** [comment]
Along with this right after.  @GregoireW 
2018-05-15 15:42:22,336+0000 WARN  [s3-transfer-manager-worker-1]  admin com.amazonaws.services.s3.AmazonS3Client - No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.

**Comment by GregoireW** [comment]
It is the 2 logs I was speaking about earlier :
> Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.

It is linked to the internal nexus process that read some byte to get the mime/type. 

> No content length specified for stream data. Stream contents will be buffered in memory and could result in out of memory errors.

The plugin do not use the multipart system from the PR, so it put data in memory then sent them at once.

**Comment by rwd5213** [comment]
So essentially I am still not using the correct jar. Is there anything else I need to do to configure it other than building the jar from your PR branch?

**Comment by GregoireW** [comment]
Building, removing previous jar, putting new jar, restarting nexus.  That should be it.

**Comment by rwd5213** [comment]
We are building nexus from scratch using the jar and is not working. Maybe there is something wrong with our installation

**Comment by GregoireW** [comment]
Building from scratch ? from source code ?  
beware there is a directory with plugins in the source code and the S3 plugin is also there (but no branch, so with the default 'single part' download). 
 If you build this, perhaps there this jar is put on nexus itself, so when you set the plugins, it is possible as both implementation exist that the wrong one is used.

**Comment by rwd5213** [comment]
This is how we are installing it. We are not installing it from source we are using a tar.gz of nexus
`aws s3 cp s3://${MGMTBootstrapBucket}/nexus/ /root/ --recursive --exclude "*" --include "nexus-3.6.1-02-unix.tar.gz"
tar -xvf /root/nexus-3.6.1-02-unix.tar.gz -C /opt/nexus/
export NEXUS_HOME=/opt/nexus/nexus-3.6.1-02

#If backup tar exists pull it down into the sonatype/nexus3/backup folder
mkdir -p /opt/nexus/sonatype-work/nexus3/backup
aws s3 cp s3://${MGMTBootstrapBucket}/nexus/ /root/ --recursive --exclude "*" --include "backupnexusfiles.tar.gz"
if [ -f /root/backupnexusfiles.tar.gz ]; then
  echo "restoring backup files from tar"
  tar -xvf /root/backupnexusfiles.tar.gz -C /opt/nexus/sonatype-work/nexus3/backup
fi
#Configure the Blobstore Jar
aws s3 cp s3://${MGMTBootstrapBucket}/nexus/ /root/ --recursive --exclude "*" --include "nexus-blobstore-s3-1.2.1-Multipart.jar"
export S3_BLOBSTORE_VERSION=1.2.1-Multipart
# export NEXUS_HOME=../nexus-internal/target/nexus-professional-3.7.0-SNAPSHOT

mkdir -p ${NEXUS_HOME}/system/org/sonatype/nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}/
cp /root/nexus-blobstore-s3-*.jar ${NEXUS_HOME}/system/org/sonatype/nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}/

sed -i.bak -e "/nexus-blobstore-file/a\\"$'\n'"<bundle>mvn:org.sonatype.nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}</bundle>" ${NEXUS_HOME}/system/org/sonatype/nexus/assemblies/nexus-base-feature/*/nexus-base-feature-*-features.xml
sed -i.bak -e "/nexus-blobstore-file/a\\"$'\n'"<bundle>mvn:org.sonatype.nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}</bundle>" ${NEXUS_HOME}/system/org/sonatype/nexus/assemblies/nexus-core-feature/*/nexus-core-feature-*-features.xml

#Configure Nexus java vmoptions
sed -i 's/-Xmx1200M/-Xmx16G/' ${NEXUS_HOME}/bin/nexus.vmoptions
sed -i 's/-XX:MaxDirectMemorySize=2G/-XX:MaxDirectMemorySize=16G/' ${NEXUS_HOME}/bin/nexus.vmoptions`

**Comment by ataylor284** [comment]
@GregoireW @rwd5213 I've been working on the S3 plugin for a while on a branch, that's finally landed on nexus-public: https://github.com/sonatype/nexus-public/tree/master/plugins/nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal

It contains a bunch of bug fixes and a simplified version of this multipart uploader.  There's an interface to add new uploaders, too.  The S3 blob store will be an integrated part of Nexus for the next release.

@GregoireW If you make a PR with the multithreaded uploader against nexus-public, I'll make sure it gets into Nexus.

**Comment by rwd5213** [comment]
Awesome! we figured out our issue with the logs being in our nexus. It was not the right jar

**Comment by GregoireW** [comment]
@ataylor284  
Do I use the standard multi-threading model or do I wait for aws SDK 2 with reactive non blocking api ?  
hum... Not sure yet.  
The non blocking api will be cleaner so perhaps I should wait.
