### ISSUE TITLE
Nexus failing to start after nexus-blobstore-s3 installation

### ISSUE THREAD

**Issue by unspotted** [sonatype/nexus-blobstore-s3#34]
* **What are you trying to do?**
Used the commands in the install script to enable nexus-blobstore-s3 on startup. Changed `S3_BLOBSTORE_VERSION` value to `3.6.1-02`. Nexus failed to start, throwing the exception pasted below.
* **What feature or behavior is this required for?**
nexus-blobstore-s3 installation
* **Anything else?**
Nexus log from an attempt to run Nexus with the `run` option
```
2017-12-07 13:07:26,405+0000 ERROR [jetty-main-1] *SYSTEM org.sonatype.nexus.bootstrap.osgi.BootstrapListener - Failed to initialize
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-oss-edition; type=karaf.feature; version="[3.6.1.02,3.6.1.02]"; filter:="(&(osgi.identity=nexus-oss-edition)(type=karaf.feature)(version>=3.6.1.02)(version<=3.6.1.02))" [caused by: Unable to resolve nexus-oss-edition/3.6.1.02: missing requirement [nexus-oss-edition/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.oss-edition; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.oss-edition/3.6.1.02: missing requirement [org.sonatype.nexus.oss-edition/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.common.app)(version>=3.6.0))" [caused by: Unable to resolve org.sonatype.nexus.common/3.6.1.02: missing requirement [org.sonatype.nexus.common/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.aopalliance.intercept)(version>=1.0.0))" [caused by: Unable to resolve org.apache.servicemix.bundles.aopalliance/1.0.0.6: missing requirement [org.apache.servicemix.bundles.aopalliance/1.0.0.6] osgi.identity; osgi.identity="root#nexus-base-feature-3.6.1.02"; type=karaf.subsystem; version="[0,0.0.0]"; resolution:=mandatory [caused by: Unable to resolve root#nexus-base-feature-3.6.1.02: missing requirement [root#nexus-base-feature-3.6.1.02] osgi.identity; osgi.identity=nexus-base-feature; type=karaf.feature; version="[3.6.1.02,3.6.1.02]" [caused by: Unable to resolve nexus-base-feature/3.6.1.02: missing requirement [nexus-base-feature/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-blobstore-s3; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02: missing requirement [org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.dataformat.cbor)(version>=2.8.0))"]]]]]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:368)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-07 13:07:26,409+0000 WARN  [jetty-main-1] *SYSTEM org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@7484ef8d{/,file:///opt/nexus/public/,UNAVAILABLE}
java.lang.RuntimeException: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-oss-edition; type=karaf.feature; version="[3.6.1.02,3.6.1.02]"; filter:="(&(osgi.identity=nexus-oss-edition)(type=karaf.feature)(version>=3.6.1.02)(version<=3.6.1.02))" [caused by: Unable to resolve nexus-oss-edition/3.6.1.02: missing requirement [nexus-oss-edition/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.oss-edition; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.oss-edition/3.6.1.02: missing requirement [org.sonatype.nexus.oss-edition/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.common.app)(version>=3.6.0))" [caused by: Unable to resolve org.sonatype.nexus.common/3.6.1.02: missing requirement [org.sonatype.nexus.common/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.aopalliance.intercept)(version>=1.0.0))" [caused by: Unable to resolve org.apache.servicemix.bundles.aopalliance/1.0.0.6: missing requirement [org.apache.servicemix.bundles.aopalliance/1.0.0.6] osgi.identity; osgi.identity="root#nexus-base-feature-3.6.1.02"; type=karaf.subsystem; version="[0,0.0.0]"; resolution:=mandatory [caused by: Unable to resolve root#nexus-base-feature-3.6.1.02: missing requirement [root#nexus-base-feature-3.6.1.02] osgi.identity; osgi.identity=nexus-base-feature; type=karaf.feature; version="[3.6.1.02,3.6.1.02]" [caused by: Unable to resolve nexus-base-feature/3.6.1.02: missing requirement [nexus-base-feature/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-blobstore-s3; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02: missing requirement [org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.dataformat.cbor)(version>=2.8.0))"]]]]]]]
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:112)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:274)
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-oss-edition; type=karaf.feature; version="[3.6.1.02,3.6.1.02]"; filter:="(&(osgi.identity=nexus-oss-edition)(type=karaf.feature)(version>=3.6.1.02)(version<=3.6.1.02))" [caused by: Unable to resolve nexus-oss-edition/3.6.1.02: missing requirement [nexus-oss-edition/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.oss-edition; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.oss-edition/3.6.1.02: missing requirement [org.sonatype.nexus.oss-edition/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.common.app)(version>=3.6.0))" [caused by: Unable to resolve org.sonatype.nexus.common/3.6.1.02: missing requirement [org.sonatype.nexus.common/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.aopalliance.intercept)(version>=1.0.0))" [caused by: Unable to resolve org.apache.servicemix.bundles.aopalliance/1.0.0.6: missing requirement [org.apache.servicemix.bundles.aopalliance/1.0.0.6] osgi.identity; osgi.identity="root#nexus-base-feature-3.6.1.02"; type=karaf.subsystem; version="[0,0.0.0]"; resolution:=mandatory [caused by: Unable to resolve root#nexus-base-feature-3.6.1.02: missing requirement [root#nexus-base-feature-3.6.1.02] osgi.identity; osgi.identity=nexus-base-feature; type=karaf.feature; version="[3.6.1.02,3.6.1.02]" [caused by: Unable to resolve nexus-base-feature/3.6.1.02: missing requirement [nexus-base-feature/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-blobstore-s3; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02: missing requirement [org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.dataformat.cbor)(version>=2.8.0))"]]]]]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:368)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-07 13:07:26,426+0000 INFO  [jetty-main-1] *SYSTEM org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@703ed7a9{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
2017-12-07 13:07:26,427+0000 ERROR [jetty-main-1] *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Failed to start
java.lang.RuntimeException: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-oss-edition; type=karaf.feature; version="[3.6.1.02,3.6.1.02]"; filter:="(&(osgi.identity=nexus-oss-edition)(type=karaf.feature)(version>=3.6.1.02)(version<=3.6.1.02))" [caused by: Unable to resolve nexus-oss-edition/3.6.1.02: missing requirement [nexus-oss-edition/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.oss-edition; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.oss-edition/3.6.1.02: missing requirement [org.sonatype.nexus.oss-edition/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.common.app)(version>=3.6.0))" [caused by: Unable to resolve org.sonatype.nexus.common/3.6.1.02: missing requirement [org.sonatype.nexus.common/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.aopalliance.intercept)(version>=1.0.0))" [caused by: Unable to resolve org.apache.servicemix.bundles.aopalliance/1.0.0.6: missing requirement [org.apache.servicemix.bundles.aopalliance/1.0.0.6] osgi.identity; osgi.identity="root#nexus-base-feature-3.6.1.02"; type=karaf.subsystem; version="[0,0.0.0]"; resolution:=mandatory [caused by: Unable to resolve root#nexus-base-feature-3.6.1.02: missing requirement [root#nexus-base-feature-3.6.1.02] osgi.identity; osgi.identity=nexus-base-feature; type=karaf.feature; version="[3.6.1.02,3.6.1.02]" [caused by: Unable to resolve nexus-base-feature/3.6.1.02: missing requirement [nexus-base-feature/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-blobstore-s3; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02: missing requirement [org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.dataformat.cbor)(version>=2.8.0))"]]]]]]]
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:112)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:274)
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-oss-edition; type=karaf.feature; version="[3.6.1.02,3.6.1.02]"; filter:="(&(osgi.identity=nexus-oss-edition)(type=karaf.feature)(version>=3.6.1.02)(version<=3.6.1.02))" [caused by: Unable to resolve nexus-oss-edition/3.6.1.02: missing requirement [nexus-oss-edition/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.oss-edition; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.oss-edition/3.6.1.02: missing requirement [org.sonatype.nexus.oss-edition/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.common.app)(version>=3.6.0))" [caused by: Unable to resolve org.sonatype.nexus.common/3.6.1.02: missing requirement [org.sonatype.nexus.common/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.aopalliance.intercept)(version>=1.0.0))" [caused by: Unable to resolve org.apache.servicemix.bundles.aopalliance/1.0.0.6: missing requirement [org.apache.servicemix.bundles.aopalliance/1.0.0.6] osgi.identity; osgi.identity="root#nexus-base-feature-3.6.1.02"; type=karaf.subsystem; version="[0,0.0.0]"; resolution:=mandatory [caused by: Unable to resolve root#nexus-base-feature-3.6.1.02: missing requirement [root#nexus-base-feature-3.6.1.02] osgi.identity; osgi.identity=nexus-base-feature; type=karaf.feature; version="[3.6.1.02,3.6.1.02]" [caused by: Unable to resolve nexus-base-feature/3.6.1.02: missing requirement [nexus-base-feature/3.6.1.02] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-blobstore-s3; type=osgi.bundle; version="[3.6.1.02,3.6.1.02]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02: missing requirement [org.sonatype.nexus.plugins.nexus-blobstore-s3/3.6.1.02] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.dataformat.cbor)(version>=2.8.0))"]]]]]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:368)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-07 13:07:26,440+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Stopping
2017-12-07 13:07:26,441+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Stopped
```

**Comment by lunderhage** [comment]
I have the same issue. I guess the script needs to install all those missing dependencies as well.

Another solution could be to build the nexus-blobstore-s3 bundle with all dependencies included, but that kind of defeats the point with OSGi.

**Comment by GregoireW** [comment]
You did not use the install.sh script ?  (to adapt to your use, change the nexus location)

**Comment by vdzhuvinov** [comment]
@GregoireW 

Hi,

We tried using the install script, but without success - it failed for two reasons I suppose: 1) it didn't install the required dependencies (as also mentioned by @lunderhage ); 2) even if these dependencies are satisfied, the blob store doesn't start correctly, and if Nexus is configured to use S3 as default store, Nexus startup will fail entirely (cited exception).

It appears the script was for an older Nexus version, and needs updating. 

I had no experience with Karaf, but after studying the documentation reached the conclusion that the steps above are the way to go (though I might still be missing something).

**Comment by GregoireW** [comment]
Dependencies are in the jar file if you build with a `mvn package` (only aws deps are needed). 

Here is mine:

```
$ unzip -t target/nexus-blobstore-s3-1.2.1.jar                                                        
    Archive:  target/nexus-blobstore-s3-1.2.1.jar
    testing: META-INF/MANIFEST.MF     OK
    testing: META-INF/                OK
    testing: META-INF/maven/          OK
    testing: META-INF/maven/org.sonatype.nexus/   OK
    testing: META-INF/maven/org.sonatype.nexus/nexus-blobstore-s3/   OK
    testing: META-INF/maven/org.sonatype.nexus/nexus-blobstore-s3/pom.properties   OK
    testing: META-INF/maven/org.sonatype.nexus/nexus-blobstore-s3/pom.xml   OK
    testing: META-INF/sisu/           OK
    testing: META-INF/sisu/javax.inject.Named   OK
    testing: aws-java-sdk-core-1.11.201.jar   OK
    testing: aws-java-sdk-kms-1.11.201.jar   OK
    testing: aws-java-sdk-s3-1.11.149.jar   OK
    testing: aws-java-sdk-sts-1.11.149.jar   OK
    testing: ion-java-1.0.2.jar       OK
    testing: org/                     OK
    testing: org/sonatype/            OK
    testing: org/sonatype/nexus/      OK
    testing: org/sonatype/nexus/blobstore/   OK
    testing: org/sonatype/nexus/blobstore/s3/   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/AmazonS3Factory.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3BlobAttributes.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3BlobStore$BlobIngester.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3BlobStore$S3Blob.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3BlobStoreDescriptor$Messages.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3BlobStoreDescriptor.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3BlobStoreMetricsStore.class   OK
    testing: org/sonatype/nexus/blobstore/s3/internal/S3PropertiesFile.class   OK
No errors detected in compressed data of target/nexus-blobstore-s3-1.2.1.jar.
```

If you got one jar from external site, check if it is a bundle or a simple jar.  (in fact if size is some kb it is a simple jar. If size is around 2MB, it is a bundle).

 The `install.sh` seems correct for me. For instance, I use this exact launcher for the docker image v3.6.2: 


```
#!/bin/sh

S3_BLOBSTORE_VERSION=1.2.1
TAG_FILE="/overload"
echo "Sonatype dir is ${SONATYPE_DIR}"

if [ ! -f $TAG_FILE ] ; then
    echo "Initializing additionals plugins"

    mkdir -p ${SONATYPE_DIR}/nexus/system/org/sonatype/nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}/
    cp /nexus-data/SETUP/nexus-blobstore-s3-*.jar ${SONATYPE_DIR}/nexus/system/org/sonatype/nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}/

    sed -i.bak -e "/nexus-blobstore-file/a\\"$'\n'"<bundle>mvn:org.sonatype.nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}</bundle>" ${SONATYPE_DIR}/nexus/system/org/sonatype/nexus/assemblies/nexus-base-feature/*/nexus-base-feature-*-features.xml

    sed -i.bak -e "/nexus-blobstore-file/a\\"$'\n'"<bundle>mvn:org.sonatype.nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}</bundle>" ${SONATYPE_DIR}/nexus/system/org/sonatype/nexus/assemblies/nexus-core-feature/*/nexus-core-feature-*-features.xml 

    touch $TAG_FILE
fi

su nexus -s "/bin/sh" -c "${SONATYPE_DIR}/start-nexus-repository-manager.sh"
```

- I create a directory on my computer `/var/lib/nexus/data` with `mkdir -p /var/lib/nexus/data/SETUP`
- I put this file as `launch.sh` (chmod +x on it) on `/var/lib/nexus/data`
- Then the plugin file ( nexus-blobstore-s3-1.2.1.jar ) in  the directory `/var/lib/nexus/data/SETUP`  
- Now you can launch: 
`docker -u 0 -v /var/lib/nexus/data:/nexus-data sonatype/nexus3:3.6.2 /nexus-data/launch.sh`

**Comment by ngraef** [comment]
@unspotted You're setting `S3_BLOBSTORE_VERSION` to the Nexus version, which is incorrect. The current version is 1.2.1. There is an open PR (#35) to fix this in `install.sh`.

**Comment by ribeaud** [comment]
@GregoireW Thanks a lot. This was really useful. This is exactly what I was looking for: Adding *S3* support to **Nexus** _Docker_ image which would make a lot of sense nowadays. Unfortunately, I am still facing following problems with this setup:

1. I was NOT able to add a **S3** blobstore in the admin UI. Did not appear in the corresponding select list. Where you able to do so?
1. This procedure does NOT work for _v3.8.0_, at least for me.

Any hint? Thanks and cheers,

christian

**Comment by ribeaud** [comment]
OK, some correction here. After having used [this](https://hub.docker.com/r/cloudsc/nexus3-blobstore-s3/) image (with minimal correction, updated to latest state), I am seeing now the **S3** blobstore in the UI.
