### ISSUE TITLE
Bundle does not work on windows instance

### ISSUE THREAD

**Issue by hiteshg40** [sonatype/nexus-blobstore-s3#49]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I am trying to configure the windows instance with the bundle - nexus-blobstore-s3. However there seems to be a problem in getting this activated. i get the following exception for any input after Nexus \run
java.lang.NumberFormatException: For input string: "bundle:list"
at java.lang.NumberFormatException.forInputString(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at com.exe4j.runtime.WinLauncher$1.run(WinLauncher.java:80)

* **What feature or behavior is this required for?**
I am trying to use AWS as the blob store for image repository
* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by splatch** [comment]
Hey @hiteshg40, seems that you placed command in wrong place. Make sure you run nexus properly because "bundle:list" might be executed only from nexus shell.
