### ISSUE TITLE
Attempt to access non-existent blob 

### ISSUE THREAD

**Issue by aplsms** [sonatype/nexus-blobstore-s3#51]
i'm build latest version of nexus and S3 blob store for docker stoped working. 
Nexus version: 3.10.0-04
S3 blobstore form git (master)

```
ARG NEXUS_VERSION=3.10.0
FROM maven:3-jdk-8-alpine AS build
ARG NEXUS_VERSION=3.10.0
ARG NEXUS_BUILD=04

ADD https://github.com/sonatype-nexus-community/nexus-repository-apt/archive/master.zip /nexus-repository-apt.zip
ADD https://github.com/sonatype/nexus-blobstore-s3/archive/master.zip /nexus-blobstore-s3.zip
#ADD https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip  /aws-java-sdk.zip
ADD aws-java-sdk.zip  /aws-java-sdk.zip

RUN  apk update \
    && apk add git \
    && rm -rf /var/cache/apk/*

RUN unzip /nexus-repository-apt.zip   \
    && cd /nexus-repository-apt-master/  \
    && sed -i "s/3.9.0-01/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml \
    && mvn \
    && mv target ../nexus-repository-apt \
    && cd ../ \
    && rm -Rf /nexus-repository-apt-master \
    && ls -la /nexus-repository-apt 

RUN unzip /nexus-blobstore-s3.zip  \
    && cd /nexus-blobstore-s3-master/ \
    && sed -i "s/3.8.0-02/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml \
    && mvn \
    && mv target ../nexus-blobstore-s3 \
    && cd ../ \
    && rm -Rf /nexus-blobstore-s3-master \
    && ls -la /nexus-blobstore-s3

RUN unzip aws-java-sdk.zip ; mv aws-java-sdk-*/lib aws-java-sdk ; rm -rf aws-java-sdk-* ; ls -la /aws-java-sdk/

#-------------------------------------------------------------------------------------------------------------------------------------------
FROM sonatype/nexus3:$NEXUS_VERSION
# Will not seem to work in sed without some magick

ARG NEXUS_VERSION=3.10.0
ARG NEXUS_BUILD=04
ARG APT_VERSION=1.0.5
ARG S3_BLOBSTORE_VERSION=1.2.1-SNAPSHOT
ARG APT_TARGET=${NEXUS_HOME}/system/net/staticsnow/nexus-repository-apt/${APT_VERSION}/
ARG S3_TARGET=${NEXUS_HOME}/system/org/sonatype/nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}/


ENV INSTALL4J_ADD_VM_PARAMS="-Xms2300m -Xmx2300m -XX:MaxDirectMemorySize=2300m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"

USER root
RUN mkdir -p ${APT_TARGET}; \
    sed -i 's@nexus-repository-yum</feature>@nexus-repository-yum</feature>\n        <feature prerequisite="false" dependency="false">nexus-repository-apt</feature>@g' /opt/sonatype/nexus/system/com/sonatype/nexus/assemblies/nexus-oss-feature/${NEXUS_VERSION}-${NEXUS_BUILD}/nexus-oss-feature-${NEXUS_VERSION}-${NEXUS_BUILD}-features.xml && \
    sed -i 's@nexus-repository-yum</feature>@nexus-repository-yum</feature>\n        <feature prerequisite="false" dependency="false">nexus-repository-apt</feature>@g' /opt/sonatype/nexus/system/com/sonatype/nexus/assemblies/nexus-pro-feature/${NEXUS_VERSION}-${NEXUS_BUILD}/nexus-pro-feature-${NEXUS_VERSION}-${NEXUS_BUILD}-features.xml && \
    sed -i 's@<feature name="nexus-repository-yum"@<feature name="nexus-repository-apt" description="net.staticsnow:nexus-repository-apt" version="1.0.5">\n        <details>net.staticsnow:nexus-repository-apt</details>\n        <bundle>mvn:net.staticsnow/nexus-repository-apt/1.0.5</bundle>\n    </feature>\n    <feature name="nexus-repository-yum"@g' /opt/sonatype/nexus/system/com/sonatype/nexus/assemblies/nexus-oss-feature/${NEXUS_VERSION}-${NEXUS_BUILD}/nexus-oss-feature-${NEXUS_VERSION}-${NEXUS_BUILD}-features.xml && \
    sed -i 's@<feature name="nexus-repository-yum"@<feature name="nexus-repository-apt" description="net.staticsnow:nexus-repository-apt" version="1.0.5">\n        <details>net.staticsnow:nexus-repository-apt</details>\n        <bundle>mvn:net.staticsnow/nexus-repository-apt/1.0.5</bundle>\n    </feature>\n    <feature name="nexus-repository-yum"@g' /opt/sonatype/nexus/system/com/sonatype/nexus/assemblies/nexus-pro-feature/${NEXUS_VERSION}-${NEXUS_BUILD}/nexus-pro-feature-${NEXUS_VERSION}-${NEXUS_BUILD}-features.xml;




RUN mkdir -p ${S3_TARGET}; \
    sed -i.bak -e "/nexus-blobstore-file/a\\"$'\n'"<bundle>mvn:org.sonatype.nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}</bundle>" ${NEXUS_HOME}/system/org/sonatype/nexus/assemblies/nexus-base-feature/*/nexus-base-feature-*-features.xml &&\
    sed -i.bak -e "/nexus-blobstore-file/a\\"$'\n'"<bundle>mvn:org.sonatype.nexus/nexus-blobstore-s3/${S3_BLOBSTORE_VERSION}</bundle>" ${NEXUS_HOME}/system/org/sonatype/nexus/assemblies/nexus-core-feature/*/nexus-core-feature-*-features.xml

COPY --from=build /nexus-repository-apt/nexus-repository-apt-${APT_VERSION}.jar ${APT_TARGET}
COPY --from=build /nexus-blobstore-s3/nexus-blobstore-s3-${S3_BLOBSTORE_VERSION}.jar ${S3_TARGET}
COPY --from=build /aws-java-sdk/aws-java-sdk-*.jar  ${S3_TARGET}

ADD Dockerfile /Dockerfile

USER nexus
``` 

Nexus version 3.8.0 had no issue with that. no one artifact can be uploaded.

Java trace: 
```
nexus    | 2018-05-01 16:44:28,437+0000 WARN  [qtp1876050708-325] docker-push org.sonatype.nexus.blobstore.s3.internal.S3BlobStore - Attempt to access non-existent blob 0 (org.sonatype.nexus.blobstore.s3.internal.S3BlobAttributes@3810f713)
nexus    | 2018-05-01 16:44:28,437+0000 WARN  [qtp1876050708-325] docker-push org.sonatype.nexus.repository.docker.internal.V2Handlers - Error: PATCH /v2/devops/nexus3-s3-apt/blobs/uploads/39009b15-75b9-414b-ba37-f18547b6b73a
nexus    | java.lang.IllegalStateException: Missing upload with uuid: 39009b15-75b9-414b-ba37-f18547b6b73a
nexus    | 	at org.sonatype.nexus.repository.docker.internal.UploadManagerImpl.ensureGetUpload(UploadManagerImpl.java:121)
nexus    | 	at org.sonatype.nexus.repository.docker.internal.UploadManagerImpl.add(UploadManagerImpl.java:64)
nexus    | 	at org.sonatype.nexus.repository.docker.internal.DockerHostedFacetImpl.uploadBlobRange(DockerHostedFacetImpl.java:561)
nexus    | 	at org.sonatype.nexus.repository.docker.internal.DockerHostedFacet$uploadBlobRange$0.call(Unknown Source)
nexus    | 	at org.sonatype.nexus.repository.docker.internal.V2Handlers$_closure4.doCall(V2Handlers.groovy:133)
nexus    | 	at sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
nexus    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nexus    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nexus    | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
nexus    | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
nexus    | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
nexus    | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
nexus    | 	at groovy.lang.Closure.call(Closure.java:414)
nexus    | 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
nexus    | 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
nexus    | 	at com.sun.proxy.$Proxy191.handle(Unknown Source)
nexus    | 	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
nexus    | 	at org.sonatype.nexus.repository.storage.UnitOfWorkHandler.handle(UnitOfWorkHandler.java:39)
nexus    | 	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
nexus    | 	at org.sonatype.nexus.repository.security.SecurityHandler.handle(SecurityHandler.java:52)
nexus    | 	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
nexus    | 	at org.sonatype.nexus.repository.view.Context$proceed$0.call(Unknown Source)
nexus    | 	at org.sonatype.nexus.repository.docker.internal.V2Handlers$_closure18.doCall(V2Handlers.groovy:294)
nexus    | 	at sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
nexus    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nexus    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nexus    | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
nexus    | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
nexus    | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
nexus    | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
nexus    | 	at groovy.lang.Closure.call(Closure.java:414)
nexus    | 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
nexus    | 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
nexus    | 	at com.sun.proxy.$Proxy191.handle(Unknown Source)
nexus    | 	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
nexus    | 	at org.sonatype.nexus.repository.view.Context$proceed.call(Unknown Source)
nexus    | 	at org.sonatype.nexus.repository.docker.internal.V2Handlers$_closure1.doCall(V2Handlers.groovy:88)
nexus    | 	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
nexus    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nexus    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nexus    | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
nexus    | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
nexus    | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
nexus    | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
nexus    | 	at groovy.lang.Closure.call(Closure.java:414)
nexus    | 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
nexus    | 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
nexus    | 	at com.sun.proxy.$Proxy191.handle(Unknown Source)
nexus    | 	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
nexus    | 	at org.sonatype.nexus.repository.view.handlers.TimingHandler.handle(TimingHandler.java:46)
nexus    | 	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
nexus    | 	at org.sonatype.nexus.repository.view.Context.start(Context.java:114)
nexus    | 	at org.sonatype.nexus.repository.view.Router.dispatch(Router.java:64)
nexus    | 	at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:52)
nexus    | 	at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:43)
nexus    | 	at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.dispatchAndSend(ViewServlet.java:211)
nexus    | 	at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.doService(ViewServlet.java:173)
nexus    | 	at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.service(ViewServlet.java:126)
nexus    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
nexus    | 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
nexus    | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
nexus    | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
nexus    | 	at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
nexus    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
nexus    | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus    | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
nexus    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus    | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus    | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
nexus    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus    | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus    | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
nexus    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus    | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
nexus    | 	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:85)
nexus    | 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
nexus    | 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
nexus    | 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
nexus    | 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
nexus    | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
nexus    | 	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:101)
nexus    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at org.sonatype.nexus.repository.httpbridge.internal.ExhaustRequestFilter.doFilter(ExhaustRequestFilter.java:71)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:108)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:68)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:102)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:98)
nexus    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus    | 	at com.google.inject.servlet.DynamicFilterPipeline.dispatch(DynamicFilterPipeline.java:104)
nexus    | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
nexus    | 	at org.sonatype.nexus.bootstrap.osgi.DelegatingFilter.doFilter(DelegatingFilter.java:73)
nexus    | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
nexus    | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
nexus    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
nexus    | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
nexus    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
nexus    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
nexus    | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
nexus    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
nexus    | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
nexus    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
nexus    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
nexus    | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
nexus    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
nexus    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
nexus    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
nexus    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
nexus    | 	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:175)
nexus    | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
nexus    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
nexus    | 	at org.eclipse.jetty.server.Server.handle(Server.java:530)
nexus    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
nexus    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
nexus    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
nexus    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
nexus    | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
nexus    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
nexus    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
nexus    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
nexus    | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
nexus    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
nexus    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
nexus    | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DarthHater** [comment]
Hi there, take a gander at #52 , this updates the plugin to use the 3.10 binaries (which is I suspect what is causing the issue). Build that branch and give it a go!

**Comment by aplsms** [comment]
nop, that's not resolve the issue. in my docker file i'm fixing that:

```
RUN unzip /nexus-blobstore-s3.zip  \
    && cd /nexus-blobstore-s3-master/ \
    && sed -i "s/3.8.0-02/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml \
    && mvn \
    && mv target ../nexus-blobstore-s3 \
    && cd ../ \
    && rm -Rf /nexus-blobstore-s3-master \
    && ls -la /nexus-blobstore-s3
```

i can build, and i can start nexus with that plugin. I even can download container from registry. but upload is failing.

**Comment by DarthHater** [comment]
Hmmm, I was scanning it visually and saw the 3.8.0 in there, so I figured I'd start there. I'll dive in a bit deeper in a bit.

**Comment by DarthHater** [comment]
@aplsms , @ataylor284 is going to merge in some stuff that we've been working on behind the scenes (s3 support is coming to the full product at some point), that may address the issue. Hang tight!

**Comment by ataylor284** [comment]
@aplsms i've pushed a fix for direct paths to https://github.com/sonatype/nexus-blobstore-s3/tree/direct-path-fix.  Can you retry with that change and let me know if that fixes the problem?  Thanks!

**Comment by aplsms** [comment]
@ataylor284 Problem fixed. thank you so much! 
Still have warnings: `2018-05-01 23:03:08,496+0000 WARN  [s3-transfer-manager-worker-1] docker-push com.amazonaws.services.s3.AmazonS3Client - No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.`
